# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: nillion_fl/heartbeat/network/heartbeat.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n,nillion_fl/heartbeat/network/heartbeat.proto"-\n\tHeartbeat\x12\x13\n\x0bstatus_code\x18\x01 \x01(\x05\x12\x0b\n\x03msg\x18\x02 \x01(\t2H\n\x10HeartbeatService\x12\x34\n\x14SubscribeToHeartbeat\x12\n.Heartbeat\x1a\n.Heartbeat"\x00(\x01\x30\x01\x62\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(
    DESCRIPTOR, "nillion_fl.heartbeat.network.heartbeat_pb2", _globals
)
if _descriptor._USE_C_DESCRIPTORS == False:
    DESCRIPTOR._options = None
    _globals["_HEARTBEAT"]._serialized_start = 48
    _globals["_HEARTBEAT"]._serialized_end = 93
    _globals["_HEARTBEATSERVICE"]._serialized_start = 95
    _globals["_HEARTBEATSERVICE"]._serialized_end = 167
# @@protoc_insertion_point(module_scope)
